sudo docker run --detach --name=test-mysql --env="MYSQL_ROOT_PASSWORD=mypassword" --publish 6603:3306 mysql #runs MySQL as a service

sudo docker run --detach --name test-wordpress --link test-mysql:mysql -p 8080:80 -d wordpress #install wordpress link to Mysql and assign to port 8080
